def Euler_Problem_1(n=1000):
    '''
    If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
    Find the sum of all the multiples of 3 or 5 below 1000.
    '''
    # compute the number of such multiples in three sets
    num_multiples_of_3   = (n-1) // 3
    num_multiples_of_5   = (n-1) // 5
    num_shared_multiples = (n-1) // (3 * 5)

    # compute the sum of each set
    def sum_one_up_to_k(k):
        return (k ** 2 + k) / 2
    sum_multiples_of_3   = sum_one_up_to_k(num_multiples_of_3) * 3
    sum_multiples_of_5   = sum_one_up_to_k(num_multiples_of_5) * 5
    sum_shared_multiples = sum_one_up_to_k(num_shared_multiples) * (3 * 5)

    # use inclusion/exclusion to compute the final answer
    retval = sum_multiples_of_3 + sum_multiples_of_5 - sum_shared_multiples
    return retval

def Euler_Problem_2(n=4000000):
    '''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    '''
    # note that for every triple starting with (1, 2, 3), the middle value is even
    def new_triple(old_triple):
        _left, _mid, _right = old_triple
        left = _mid + _right
        mid = left + _right
        right = left + mid
        return (left, mid, right)

    retval = 0
    current_triple = (1, 2, 3)
    while True:
        if current_triple[1] > n:
            break
        retval += current_triple[1]
        current_triple = new_triple(current_triple)
    return retval

def Euler_Problem_3(n=600851475143):
    '''
    The prime factors of 13195 are 5, 7, 13 and 29.
    What is the largest prime factor of the number 600851475143 ?
    '''
    # start from 2 and keep dividing
    from subroutines import least_divisor
    greatest_divisor = 2
    value            = n
    while greatest_divisor < value:
        greatest_divisor = least_divisor(value, greatest_divisor)
        value           /= greatest_divisor

    return greatest_divisor

def Euler_Problem_4(n=3):
    '''
    A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 * 99.
    Find the largest palindrome made from the product of two 3-digit numbers.
    '''
    from subroutines import is_a_palindrome
    assert n >= 2
    greatest_product = 0
    # brute-force approach that searches the high end of possible products
    upper_bound = 10 ** n - 1
    lower_bound = int(0.9 * upper_bound)
    for p in range(upper_bound, lower_bound, -1):
        for q in range(upper_bound, lower_bound, -1):
            candidate = p * q
            if candidate > greatest_product:
                if is_a_palindrome(candidate):
                    greatest_product = candidate
    return greatest_product

def Euler_Problem_5(n=20):
    '''
    2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
    What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
    '''
    from subroutines import least_divisor

    def subproblem(num, cache):
        '''
        Uses a cache to store intermediate results.
        '''
        assert isinstance(num, int)
        assert num > 0 
        # base case
        if num == 1:
            cache[num] = 1
            return cache[num] 

        # recursion / dynamic programming
        if not num-1 in cache.keys():
            prev = subproblem(num-1, cache)
        if prev % num == 0:
            cache[num] = prev
        else:
            # take advantage of the fact that any divisor of num divides prev
            factor = least_divisor(num, floor=2)
            cache[num] = prev * factor
        return cache[num]

    solution_cache = {}
    return subproblem(n, solution_cache)

def Euler_Problem_6(n=100):
    '''
    The sum of the squares of the first ten natural numbers is,
    1^2 + 2^2 + ... + 10^2 = 385
    The square of the sum of the first ten natural numbers is,
    (1 + 2 + ... + 10)^2 = 55^2 = 3025
    Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 - 385 = 2640.
    Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
    '''
    # looks like brute force gives you O(n) or O(n logn), which is not bad...
    # but we can do better with mathematical insight.
    def sum_of_integer_squares(k):
        '''
        Use the formula 1^2 + 2^2 + ... + n^2 = (n * (n+1) * (2n+1)) / 6.
        '''
        return (k * (k+1) * (2*k + 1)) / 6
   
    def square_of_integer_sums(k):
        '''
        Use the formula 1 + 2 + ... + n = n (n+1) / 2.
        '''
        return (n * (n+1) / 2) ** 2

    # O(logn) basic operations
    sqsum = square_of_integer_sums(n)
    sumsq = sum_of_integer_squares(n)
    return int(sqsum - sumsq)

def Euler_Problem_7(n=10001):
    '''
    By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
    What is the 10001st prime number?
    '''
    from subroutines import has_nontrivial_divisor
    
    # brute force: check numbers one by one
    value = 1
    num_primes = 0
    while num_primes < n:
        value += 1
        if not has_nontrivial_divisor(value):
            num_primes += 1
    return value

def Euler_Problem_8(n=13):
    '''
    The four adjacent digits in the 1000-digit number that have the greatest product are 9 * 9 * 8 * 9 = 5832.
    73167176531330624919225119674426574742355349194934
    96983520312774506326239578318016984801869478851843
    85861560789112949495459501737958331952853208805511
    12540698747158523863050715693290963295227443043557
    66896648950445244523161731856403098711121722383113
    62229893423380308135336276614282806444486645238749
    30358907296290491560440772390713810515859307960866
    70172427121883998797908792274921901699720888093776
    65727333001053367881220235421809751254540594752243
    52584907711670556013604839586446706324415722155397
    53697817977846174064955149290862569321978468622482
    83972241375657056057490261407972968652414535100474
    82166370484403199890008895243450658541227588666881
    16427171479924442928230863465674813919123162824586
    17866458359124566529476545682848912883142607690042
    24219022671055626321111109370544217506941658960408
    07198403850962455444362981230987879927244284909188
    84580156166097919133875499200524063689912560717606
    05886116467109405077541002256983155200055935729725
    71636269561882670428252483600823257530420752963450
    Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
    '''
    from functools import reduce
    # preprocessing
    series = '''\
    73167176531330624919225119674426574742355349194934\
    96983520312774506326239578318016984801869478851843\
    85861560789112949495459501737958331952853208805511\
    12540698747158523863050715693290963295227443043557\
    66896648950445244523161731856403098711121722383113\
    62229893423380308135336276614282806444486645238749\
    30358907296290491560440772390713810515859307960866\
    70172427121883998797908792274921901699720888093776\
    65727333001053367881220235421809751254540594752243\
    52584907711670556013604839586446706324415722155397\
    53697817977846174064955149290862569321978468622482\
    83972241375657056057490261407972968652414535100474\
    82166370484403199890008895243450658541227588666881\
    16427171479924442928230863465674813919123162824586\
    17866458359124566529476545682848912883142607690042\
    24219022671055626321111109370544217506941658960408\
    07198403850962455444362981230987879927244284909188\
    84580156166097919133875499200524063689912560717606\
    05886116467109405077541002256983155200055935729725\
    71636269561882670428252483600823257530420752963450\
    '''.replace(' ', '')
    series = list(map(int, list(series)))
    assert len(series) > n

    # linear scan of all products
    tmp_prod = reduce(lambda a, b: a * b, series[0:n])
    max_prod = tmp_prod
    # attempt to cheat the product at O(1)
    for k in range(1, len(series)-n):
        # attempt works if the term to be removed is nonzero
        if series[k-1] > 0:
            tmp_prod = tmp_prod * series[k+n-1] / series[k-1]
        # attmpt fails is the term to be removed is zero
        else:
            tmp_prod = reduce(lambda a, b: a * b, series[k:(k+n)])
        # update product
        if tmp_prod > max_prod:
            max_prod = tmp_prod
    return max_prod

def Euler_Problem_9(n=1000):
    '''
    A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
    a^2 + b^2 = c^2
    For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.
    There exists exactly one Pythagorean triplet for which a + b + c = 1000.
    Find the product abc.
    '''
    import math
    assert n > 10
    # first assume that a <= b < c < n/2. Then, for c to be an integer we can't have a=b.
    # hence assume that a < b < c and that n/3 < 3.

    # brute-force O(n^2) approach
    for c in range(n//2, n//3, -1):
        c_sq = c ** 2
        for b in range(c-1, int(c / math.sqrt(2)), -1):
            a = n - c - b
            if a ** 2 + b ** 2 == c_sq:
                return a * b * c
    return -1

def Euler_Problem_10(n=2000000):
    '''
    The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
    Find the sum of all the primes below two million.
    '''
    def divisible_by_prime(num, primes):
        assert num >= 2
        for _p in primes:
            if num % _p == 0:
                return True
        return False
    
    # brute force: check numbers one by one, starting at 3
    # also maintain a list of primes to divide by
    value = 2
    current_primes = [2]
    while value < n-1:
        if value % 10000 == 0:
            print(value)
        value += 1
        if not divisible_by_prime(value, current_primes):
            current_primes.append(value)
    return sum(current_primes)

def Euler_Problem_11(k=4):
    '''
    In the 20 * 20 grid below, four numbers along a diagonal line have been marked in red.
    08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
    49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
    81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
    52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
    22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
    24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
    32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
    67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
    24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
    21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
    78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
    16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
    86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
    19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
    04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
    88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
    04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
    20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
    20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
    01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
    The product of these numbers is 26 * 63 * 78 * 14 = 1788696.
    What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20 * 20 grid?
    '''
    # This problem always takes at least O(M^2) where M is the size of the grid.
    # Here's the argument:
    # Consider the reduced problem where we only care about adjacent numbers in the horizontal direction. Then we need a linear scan in each row, giving a running time of O(M^2).
    # Note the brute force takes O(M^2), which is good enough in asymtotic scaling.

    # construct the array
    import numpy as np
    arr_in_str_form = '''
    08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
    49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
    81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
    52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
    22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
    24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
    32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
    67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
    24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
    21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
    78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
    16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
    86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
    19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
    04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
    88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
    04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
    20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
    20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
    01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
    '''
    arr_in_str_form = [_x for _x in arr_in_str_form.split('\n') if len(_x) > 0]
    arr = [[int(_z) for _z in _y.split(' ') if len(_z) > 0] for _y in arr_in_str_form]
    arr = np.array([_a for _a in arr if len(_a) > 0])
    assert arr.shape == (20, 20)
    
    # set up max product variable
    max_prod = 0

    # consider horizontal and vertical
    for i in range(0, 20):
        for j in range(0, 20-k+1):
            # horizontal
            value = 1
            for shift in range(0, k):
                value *= arr[i][j+shift]
            if value > max_prod:
                max_prod = value

            # vertical
            value = 1
            for shift in range(0, k):
                value *= arr[j+shift][i]
            if value > max_prod:
                max_prod = value

    # consider diagonal directions 
    for i in range(0, 20-k+1):
        for j in range(0, 20-k+1):
            # upper-left-to-lower-right
            value = 1
            for shift in range(0, k):
                value *= arr[i+shift][j+shift]
            if value > max_prod:
                max_prod = value

            # upper-right-to-lower-left
            value = 1
            for shift in range(0, k):
                value *= arr[i+shift][20-1-j-shift]
            if value > max_prod:
                max_prod = value

    return max_prod

def Euler_Problem_12(n=500, trial_bound=10**6):
    '''
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
    We can see that 28 is the first triangle number to have over five divisors.
    What is the value of the first triangle number to have over five hundred divisors?
    '''
    from subroutines import Factorizer, get_num_divisors

    # initialize cache
    fac = Factorizer(bound=trial_bound)
    candidate  = 1
    cache_num_divisors = {1: 1}
    # dynamic programming execution assuming that the candidate is bounded
    # here's the trick: we don't check the number to be outputed, but its near-squarer-root.
    while candidate < trial_bound:
        candidate += 1
        factors = fac.factorize(candidate)
        cache_num_divisors[candidate] = get_num_divisors(factors)
        # calculate the number of divisors of (candidate-1) * candidate / 2
        if candidate % 2 == 0:
            prod_num_divisors = cache_num_divisors[candidate // 2] * cache_num_divisors[candidate - 1]
        else:
            prod_num_divisors = cache_num_divisors[candidate] * cache_num_divisors[(candidate - 1) // 2]
        if prod_num_divisors > n:
            return prod_num_divisors, int((candidate - 1) * candidate / 2)
    return -1        

def Euler_Problem_13():
    '''
    Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.
    '''
    raw_list = '''
    37107287533902102798797998220837590246510135740250
    46376937677490009712648124896970078050417018260538
    74324986199524741059474233309513058123726617309629
    91942213363574161572522430563301811072406154908250
    23067588207539346171171980310421047513778063246676
    89261670696623633820136378418383684178734361726757
    28112879812849979408065481931592621691275889832738
    44274228917432520321923589422876796487670272189318
    47451445736001306439091167216856844588711603153276
    70386486105843025439939619828917593665686757934951
    62176457141856560629502157223196586755079324193331
    64906352462741904929101432445813822663347944758178
    92575867718337217661963751590579239728245598838407
    58203565325359399008402633568948830189458628227828
    80181199384826282014278194139940567587151170094390
    35398664372827112653829987240784473053190104293586
    86515506006295864861532075273371959191420517255829
    71693888707715466499115593487603532921714970056938
    54370070576826684624621495650076471787294438377604
    53282654108756828443191190634694037855217779295145
    36123272525000296071075082563815656710885258350721
    45876576172410976447339110607218265236877223636045
    17423706905851860660448207621209813287860733969412
    81142660418086830619328460811191061556940512689692
    51934325451728388641918047049293215058642563049483
    62467221648435076201727918039944693004732956340691
    15732444386908125794514089057706229429197107928209
    55037687525678773091862540744969844508330393682126
    18336384825330154686196124348767681297534375946515
    80386287592878490201521685554828717201219257766954
    78182833757993103614740356856449095527097864797581
    16726320100436897842553539920931837441497806860984
    48403098129077791799088218795327364475675590848030
    87086987551392711854517078544161852424320693150332
    59959406895756536782107074926966537676326235447210
    69793950679652694742597709739166693763042633987085
    41052684708299085211399427365734116182760315001271
    65378607361501080857009149939512557028198746004375
    35829035317434717326932123578154982629742552737307
    94953759765105305946966067683156574377167401875275
    88902802571733229619176668713819931811048770190271
    25267680276078003013678680992525463401061632866526
    36270218540497705585629946580636237993140746255962
    24074486908231174977792365466257246923322810917141
    91430288197103288597806669760892938638285025333403
    34413065578016127815921815005561868836468420090470
    23053081172816430487623791969842487255036638784583
    11487696932154902810424020138335124462181441773470
    63783299490636259666498587618221225225512486764533
    67720186971698544312419572409913959008952310058822
    95548255300263520781532296796249481641953868218774
    76085327132285723110424803456124867697064507995236
    37774242535411291684276865538926205024910326572967
    23701913275725675285653248258265463092207058596522
    29798860272258331913126375147341994889534765745501
    18495701454879288984856827726077713721403798879715
    38298203783031473527721580348144513491373226651381
    34829543829199918180278916522431027392251122869539
    40957953066405232632538044100059654939159879593635
    29746152185502371307642255121183693803580388584903
    41698116222072977186158236678424689157993532961922
    62467957194401269043877107275048102390895523597457
    23189706772547915061505504953922979530901129967519
    86188088225875314529584099251203829009407770775672
    11306739708304724483816533873502340845647058077308
    82959174767140363198008187129011875491310547126581
    97623331044818386269515456334926366572897563400500
    42846280183517070527831839425882145521227251250327
    55121603546981200581762165212827652751691296897789
    32238195734329339946437501907836945765883352399886
    75506164965184775180738168837861091527357929701337
    62177842752192623401942399639168044983993173312731
    32924185707147349566916674687634660915035914677504
    99518671430235219628894890102423325116913619626622
    73267460800591547471830798392868535206946944540724
    76841822524674417161514036427982273348055556214818
    97142617910342598647204516893989422179826088076852
    87783646182799346313767754307809363333018982642090
    10848802521674670883215120185883543223812876952786
    71329612474782464538636993009049310363619763878039
    62184073572399794223406235393808339651327408011116
    66627891981488087797941876876144230030984490851411
    60661826293682836764744779239180335110989069790714
    85786944089552990653640447425576083659976645795096
    66024396409905389607120198219976047599490197230297
    64913982680032973156037120041377903785566085089252
    16730939319872750275468906903707539413042652315011
    94809377245048795150954100921645863754710598436791
    78639167021187492431995700641917969777599028300699
    15368713711936614952811305876380278410754449733078
    40789923115535562561142322423255033685442488917353
    44889911501440648020369068063960672322193204149535
    41503128880339536053299340368006977710650566631954
    81234880673210146739058568557934581403627822703280
    82616570773948327592232845941706525094512325230608
    22918802058777319719839450180888072429661980811197
    77158542502016545090413245809786882778948721859617
    72107838435069186155435662884062257473692284509516
    20849603980134001723930671666823555245252804609722
    53503534226472524250874054075591789781264330331690
    '''
    # take the first 16 digits and throw away the rest.
    arr_in_str_form = [_x for _x in raw_list.split('\n') if len(_x.replace(' ', '')) > 0]
    arr = [int(_y[:16]) for _y in arr_in_str_form]
    assert len(arr) == 100

    return str(sum(arr))[:10]

def Euler_Problem_14(n=1000000):
    '''
    The following iterative sequence is defined for the set of positive integers:
    n -> n/2 (n is even)
    n -> 3n + 1 (n is odd)
    Using the rule above and starting with 13, we generate the following sequence:
    13 -> 40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1
    It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.
    Which starting number, under one million, produces the longest chain?
    NOTE: Once the chain starts the terms are allowed to go above one million.
    '''
    def collatz(num):
        '''
        Subroutine to calculate the next term in the collatz sequence.
        '''
        assert num > 0 and isinstance(num, int)
        next_term = (num // 2) if (num % 2 == 0) else (3 * num + 1)
        return next_term

    def lookup_collatz_length(num, cache):
        ''' 
        Uses recursion with cache for "non-sequential dynamic programming".
        '''
        assert cache[1] == 1
        if num in cache.keys():
            return cache[num]
        else:
            length = lookup_collatz_length(collatz(num), cache) + 1
            cache[num] = length
            return length

    # initialize cache
    solution_cache = {1: 1}
    max_length = 1
    best_start = 1
    for k in range(1, n):
        _length = lookup_collatz_length(k, solution_cache)
        if _length > max_length:
            max_length = _length
            best_start = k
    # reconstuct the longest collatz sequence        
    best_chain = []
    value = best_start
    while value > 1:
        best_chain.append(value)
        value = collatz(value)
    best_chain.append(1)
    return best_start, max_length, best_chain

def Euler_Problem_15(n=20):
    '''
    Starting in the top left corner of a 2 * 2 grid, and only being able to move to the right and down, there are exactly 6 routes to the bottom right corner.
    How many such routes are there through a 20 * 20 grid?
    '''
    # this is classic "2n choose n".
    num_routes = 1.0
    # trick to compute (2n)! / n! with less risk of numeric overflow
    for k in range(1, n+1):
        num_routes *= (n+k) / k
    return round(num_routes)

def Euler_Problem_16(n=1000):
    '''
    2 ^ 15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
    What is the sum of the digits of the number 2 ^ 1000?
    '''
    # 2 ^ 1000 is between 10^250 and 10^333, which is too large for typical data types.
    # However, one can easily store by digit.
    from subroutines import multiply_by_constant

    # run subroutine n times
    num = {0: 1}
    for k in range(0, n):
        num = multiply_by_constant(num, 2)
    return sum(num.values())  

def Euler_Problem_17(n=1000):
    '''
    If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
    If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?
    NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.
    '''
    hard_coded_mapping = {
            0: 0, # "zero" in this case is really "nothing"
            1: 3, # "one"
            2: 3, # "two"
            3: 5, # etc.
            4: 4,
            5: 4,
            6: 3,
            7: 5,
            8: 5,
            9: 4,
            10: 3,
            11: 6,
            12: 6,
            13: 8,
            14: 8,
            15: 7,
            16: 7,
            17: 9,
            18: 8,
            19: 8,
            20: 6,
            30: 6,
            40: 5,
            50: 5,
            60: 5,
            70: 7,
            80: 6,
            90: 6
            }
    def subroutine_small(num):
        '''
        Assumes that the number is below a hundred.
        '''
        assert isinstance(num, int) and (num >= 0) and (num < 100), num
        if num in hard_coded_mapping.keys():
            return hard_coded_mapping[num]
        else:
            floor_to_ten = (num // 10) * 10
            modulos_ten  = num % 10
            return hard_coded_mapping[floor_to_ten] + hard_coded_mapping[modulos_ten]

    def count_digits(num):
        '''
        Assumes that the number is below a million.
        '''
        assert isinstance(num, int) and (num > 0), num
        num_thousands = num // 1000
        num_hundreds  = (num % 1000) // 100
        num_small     = num % 100

        part_below_hundred = subroutine_small(num_small)
        digits = part_below_hundred
        if num_thousands > 0:
            digits += count_digits(num_thousands) + 8 # 8 from "thousand"
        if num_hundreds > 0:
            digits += count_digits(num_hundreds) + 7 # 7 from "hundred"
        if (num_thousands > 0 or num_hundreds > 0) and part_below_hundred > 0:
            digits += 3 # 3 from "and"
        return digits
    
    def test():
        from random import randint
        for k in range(0, 10):
            trial = randint(1, 10000)
            print(trial, count_digits(trial))
        for k in range(1, 20):
            trial = k * 50
            print(trial, count_digits(trial))

    total_digits = 0
    for k in range(1, n+1):
        val = count_digits(k)
        #print(k, val)
        total_digits += val
    return total_digits

def Euler_Problem_18(row_idx=-1):
    '''
    By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.
    
       3
      7 4
     2 4 6
    8 5 9 3
    That is, 3 + 7 + 4 + 9 = 23.
    Find the maximum total from top to bottom of the triangle below:
                  75
                 95 64
                17 47 82
               18 35 87 10
              20 04 82 47 65
             19 01 23 75 03 34
            88 02 77 73 07 63 67
           99 65 04 28 06 16 70 92
          41 41 26 56 83 40 80 70 33
         41 48 72 33 47 32 37 16 94 29
        53 71 44 65 25 43 91 52 97 51 14
       70 11 33 28 77 73 17 78 39 68 17 57
      91 71 52 38 17 14 91 43 58 50 27 29 48
     63 66 04 68 89 53 67 30 73 16 69 87 40 31
    04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
    NOTE: As there are only 16384 routes, it is possible to solve this problem by trying every route. However, Problem 67, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)
    '''
    inp_arr = '''
    75
    95 64
    17 47 82
    18 35 87 10
    20 04 82 47 65
    19 01 23 75 03 34
    88 02 77 73 07 63 67
    99 65 04 28 06 16 70 92
    41 41 26 56 83 40 80 70 33
    41 48 72 33 47 32 37 16 94 29
    53 71 44 65 25 43 91 52 97 51 14
    70 11 33 28 77 73 17 78 39 68 17 57
    91 71 52 38 17 14 91 43 58 50 27 29 48
    63 66 04 68 89 53 67 30 73 16 69 87 40 31
    04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
    '''
    arr = [[int(_z) for _z in _y.split(' ') if len(_z) > 0] for _y in inp_arr.split('\n')]
    arr = [_l for _l in arr if len(_l) > 0]

    # dynamic programming: tile it up by cumulative scores, row by row
    points = []
    for i, _row in enumerate(arr):
        # base case: the first row
        if i == 0:
            points.append(_row[:])
        else:
            tmp_row = []
            last_idx = len(_row) - 1
            for j, _num in enumerate(_row):
                # special case: the left-most element of a row
                if j == 0:
                    parent_value = points[i-1][0]
                # special case: the right-most element of a row
                elif j == last_idx:
                    parent_value = points[i-1][j-1]
                # common case: a middle element of a row
                else:
                    parent_value = max(points[i-1][j-1], points[i-1][j]) 
                tmp_row.append(parent_value + _row[j])
            points.append(tmp_row[:])
    return max(points[row_idx])

def Euler_Problem_19(n=2000):
    '''
    You are given the following information, but you may prefer to do some research for yourself.
    1 Jan 1900 was a Monday.
    Thirty days has September,
    April, June and November.
    All the rest have thirty-one,
    Saving February alone,
    Which has twenty-eight, rain or shine.
    And on leap years, twenty-nine.
    A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
    How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?
    '''
    month_to_days_common = {1: 31, 2: 28, 3: 31, 4: 30, 5: 31, 6: 30,
            7: 31, 8: 31, 9: 30, 10: 31, 11: 30, 12: 31}
    month_to_days_leap = {1: 31, 2: 29, 3: 31, 4: 30, 5: 31, 6: 30,
            7: 31, 8: 31, 9: 30, 10: 31, 11: 30, 12: 31}

    def count_Sunday_1sts(year, first_day):
        '''
        Subroutine to count the number of 1st Sundays in a year.
        '''
        # set up calculation
        month_to_days = dict(month_to_days_common)
        if year % 4 == 0:
            if (year % 100 != 0) or (year % 400 == 0):
                month_to_days = dict(month_to_days_leap)
        val = first_day

        # loop over months
        count = 0
        months = []
        for _month in range(1, 13):
            if val % 7 == 0:
                count += 1
                months.append((year, _month))
            val += month_to_days[_month]
        return count, val % 7, months[:]

    # Jan 1 1900 was a Monday
    first_day = 1
    total_count = 0
    match_months = []
    for _year in range(1900, n+1):
        count, first_day, months = count_Sunday_1sts(_year, first_day)
        total_count += count
        match_months += months
    # the problem asks for Jan 1, 1901 to Dec 31, 2000, so we exclude 1900
    return total_count - count_Sunday_1sts(1900, 1)[0]

def Euler_Problem_20(n=100):
    '''
    n! means n * (n - 1) * ... * 3 * 2 * 1

    For example, 10! = 10 * 9 * ... * 3 * 2 * 1 = 3628800,
    and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
    
    Find the sum of the digits in the number 100!
    '''
    # 100! is between 10^100 and 10^200, which is too large for typical data types.
    # However, one can easily store by digit.
    from subroutines import multiply_by_constant

    # run subroutine n times
    num = {0: 1}
    for k in range(1, n+1):
        num = multiply_by_constant(num, k)
    return sum(num.values())  

def Euler_Problem_21(n=10000):
    '''
    Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
    If d(a) = b and d(b) = a, where a != b, then a and b are an amicable pair and each of a and b are called amicable numbers.
    For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.
    Evaluate the sum of all the amicable numbers under 10000.
    '''

    from subroutines import Factorizer, get_sum_proper_divisors

    fac = Factorizer(bound=n)
    def check_amicable(a):
        a_factorization = fac.factorize(a)
        b = get_sum_proper_divisors(a_factorization)
        b_factorization = fac.factorize(b)
        if a == get_sum_proper_divisors(b_factorization) and a != b:
            return (a, b)
        return False

    # initialize answer
    candidate = 1
    amicables = []

    while candidate < n:
        candidate += 1
        amicable_pair = check_amicable(candidate)
        if amicable_pair:
            a, b = amicable_pair
            if a < b:
                amicables += [a, b]
    return amicables        

def Euler_Problem_22():
    '''
    Using names.txt (right click and 'Save Link/Target As...'), a 46K text file containing over five-thousand first names, begin by sorting it into alphabetical order. Then working out the alphabetical value for each name, multiply this value by its alphabetical position in the list to obtain a name score.

    For example, when the list is sorted into alphabetical order, COLIN, which is worth 3 + 15 + 12 + 9 + 14 = 53, is the 938th name in the list. So, COLIN would obtain a score of 938 * 53 = 49714.

    What is the total of all the name scores in the file?
    '''
    from custom_config import get_attachment_path 
    with open(get_attachment_path(22), 'r') as f:
        names = sorted([eval(_x) for _x in f.read().split(',')])
    char_to_int = {
            'A':  1, 'B':  2, 'C':  3, 'D':  4, 'E':  5, 'F':  6, 'G':  7,
            'H':  8, 'I':  9, 'J': 10, 'K': 11, 'L': 12, 'M': 13, 'N': 14,
            'O': 15, 'P': 16, 'Q': 17, 'R': 18, 'S': 19, 'T': 20, 'U': 21,
            'V': 22, 'W': 23, 'X': 24, 'Y': 25, 'Z': 26
            }

    def name_to_score(name):
        return sum([char_to_int[_char] for _char in list(name)])

    scores = [(i+1) * name_to_score(_name) for i, _name in enumerate(names)]
    return sum(scores)

def Euler_Problem_23():
    '''
    A perfect number is a number for which the sum of its proper divisors is exactly equal to the number. For example, the sum of the proper divisors of 28 would be 1 + 2 + 4 + 7 + 14 = 28, which means that 28 is a perfect number.
    A number n is called deficient if the sum of its proper divisors is less than n and it is called abundant if this sum exceeds n.
    As 12 is the smallest abundant number, 1 + 2 + 3 + 4 + 6 = 16, the smallest number that can be written as the sum of two abundant numbers is 24. By mathematical analysis, it can be shown that all integers greater than 28123 can be written as the sum of two abundant numbers. However, this upper limit cannot be reduced any further by analysis even though it is known that the greatest number that cannot be expressed as the sum of two abundant numbers is less than this limit.
    Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.
    '''
    from subroutines import Factorizer, get_sum_proper_divisors
    
    fac = Factorizer(bound=28123)
    def is_abundant(num):
        factorization = fac.factorize(num)
        sum_proper_divisors = get_sum_proper_divisors(factorization)
        if sum_proper_divisors > num:
            return True
        else:
            return False

    def is_sum_of_two_abundant(candidate, abundants):
        '''
        Determine whether candidate is the sum of two abundant numbers.
        abundants -- dict with abundant numbers as keys.
        '''
        for a in abundants.keys():
            b = candidate - a
            if b in abundants.keys():
                return True
        return False

    # determine abundant numbers that are below the analytic bound
    abundant_numbers = dict()
    for k in range(0, 28123):
        if is_abundant(k):
            abundant_numbers[k] = 1

    # determine which numbers cannot be written as a sum of two abundant numbers
    not_sum_of_two_abundant = []
    for s in range(0, 28123):
        if not is_sum_of_two_abundant(s, abundant_numbers):
            not_sum_of_two_abundant.append(s)
    
    return sum(not_sum_of_two_abundant)

def Euler_Problem_24(digits=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], n=1000000):
    '''
    A permutation is an ordered arrangement of objects. For example, 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of the permutations are listed numerically or alphabetically, we call it lexicographic order. The lexicographic permutations of 0, 1 and 2 are:
    012   021   102   120   201   210
    What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?
    '''
    # insight: there are 10 numbers from 0 to 9, i.e. 10! = 3628800 permutations.
    # -> there are 362880 such permutations that start with 0.
    # -> there are 1086400 such permutations that start with 0, 1, or 2. 
    from subroutines import factorial

    assert factorial(len(digits)) > n - 1
    permutation = ''
    digits_left = digits[:] 
    perm_position = n - 1
    while len(digits_left) > 0:
        perms_per_first_digit = factorial(len(digits_left) - 1)
        next_idx = perm_position // perms_per_first_digit
        permutation += digits_left.pop(next_idx)
        perm_position -= next_idx * perms_per_first_digit
    return permutation
       
def Euler_Problem_25(n=1000):
    '''
    The Fibonacci sequence is defined by the recurrence relation:
    Fn = Fn-1 + Fn-2, where F1 = 1 and F2 = 1.
    Hence the first 12 terms will be:
    F1 = 1
    F2 = 1
    F3 = 2
    F4 = 3
    F5 = 5
    F6 = 8
    F7 = 13
    F8 = 21
    F9 = 34
    F10 = 55
    F11 = 89
    F12 = 144
    The 12th term, F12, is the first term to contain three digits.
    What is the index of the first term in the Fibonacci sequence to contain 1000 digits?
    '''
    # a geometric series with a common ratio of (sqrt(5)+1)/2 is an excellent numerical approximation of the Fibonacci sequence.
    
    from math import sqrt, log, exp, ceil
    # use F8 thru F12 to estimate the log of the 10th term of the geometric series
    log_10th_term = (log(21) + log(34) + log(55) + log(89) + log(144)) / 5
    log_ratio = log((sqrt(5) + 1) / 2)
    # n digits is on the order of 10^(n-1)
    diff_index = ((n-1) * log(10) - log_10th_term) / log_ratio
    return ceil(diff_index) + 10

def Euler_Problem_26(n=1000):
    '''
    A unit fraction contains 1 in the numerator. The decimal representation of the unit fractions with denominators 2 to 10 are given:
    1/2	= 	0.5
    1/3	= 	0.(3)
    1/4	= 	0.25
    1/5	= 	0.2
    1/6	= 	0.1(6)
    1/7	= 	0.(142857)
    1/8	= 	0.125
    1/9	= 	0.(1)
    1/10= 	0.1
    Where 0.1(6) means 0.166666..., and has a 1-digit recurring cycle. It can be seen that 1/7 has a 6-digit recurring cycle.
    Find the value of d < 1000 for which 1/d contains the longest recurring cycle in its decimal fraction part.
    '''
    # a bit of mathematical insight is helpful here.
    # if d is divisible by 2 or 5, d has the same number of digits in the 1/d recurring cycle as (d/2) or (d/5) respectively.
    # assuming that d is not divisible by 2 or 5, then the smallest m with (10^m - 1) divisible by d gives the length of the recurring cycle.

    def remove_2_5_factors(num):
        '''
        Divide a number by 2 and 5 until it becomes coprime with 2 and 5.
        '''
        if num % 2 == 0:
            return remove_2_5_factors(num // 2)
        if num % 5 == 0:
            return remove_2_5_factors(num // 5)
        return num

    cache_cycle_length = {}
    for d in range(2, n):
        d_equivalent = remove_2_5_factors(d)
        # base case: d has no prime factors other than 2 and 5
        if d_equivalent == 1:
            cache_cycle_length[d] = 0
        # recursive case: d is divisible by 2 or 5 but has other prime factors
        elif d_equivalent in cache_cycle_length.keys():
            cache_cycle_length[d] = cache_cycle_length[d_equivalent]
        # base case: d is not divisible by 2 or 5
        else:
            # one should be alerted if the for loop fails to update the cycle length.
            cache_cycle_length[d] = -1
            for m in range(1, 1000):
                if (10**m - 1) % d == 0:
                    cache_cycle_length[d] = m
                    break
    if min(cache_cycle_length.values()) < 0:
        print('Warning: some number has longer cycle length than we screened for.')
    d_to_return = max(cache_cycle_length.keys(), key=lambda x: cache_cycle_length[x])
    return d_to_return, cache_cycle_length[d_to_return]

def Euler_Problem_27(k=1000):
    '''
    Euler discovered the remarkable quadratic formula:
    n2+n+41
    It turns out that the formula will produce 40 primes for the consecutive integer values 0<=n<=39. However, when n=40,402+40+41=40(40+1)+41 is divisible by 41, and certainly when n=41,412+41+41 is clearly divisible by 41.
    The incredible formula n^2-79n+1601 was discovered, which produces 80 primes for the consecutive values 0<=n<=79. The product of the coefficients, -79 and 1601, is -126479.
    Considering quadratics of the form:
    n^2+an+b, where |a|<1000 and |b|<=1000
    where |n| is the modulus/absolute value of n
    e.g. |11|=11 and |-4|=4
    Find the product of the coefficients, a and b, for the quadratic expression that produces the maximum number of primes for consecutive values of n, starting with n=0.
    '''
    # consider the n=0 and n=1 cases. b must be a prime number, thus positive; 1+a+b must be a prime number, so a > -b. 
    # n^2+an must be consistently even or consistently odd, but it can only be consistently even (because 'consistently odd' cannot happen no matter what a is). This also implies that both a and b need to be odd.
    # -> idea: first determine all the possible values of b. Then for each b, there are O(b) values to a to try.

    from subroutines import Factorizer, is_prime_given_factorization

    fac = Factorizer()
    def prime_quadratic_sequence(a, b):
        '''
        Determine the sequence of primes n^2+an+b parametrized by a and b. Uses a cache to read and store factorizations.
        '''
        n = 0
        terms = []
        while True:
            _term = n * (n + a) + b
            _term_factorization = fac.factorize(_term)
            if is_prime_given_factorization(_term_factorization):
                n += 1
                terms.append(_term)
            else:
                break
        return terms

    odd_primes_under_k = []
    # scan for odd primes as possible values of b. 
    for _trial in range(3, k+1):
        _factorization = fac.factorize(_trial)
        if is_prime_given_factorization(_factorization):
            odd_primes_under_k.append(_trial)
                
    # loop over possible values of b
    max_length = 0
    best_tuple = None
    best_sequence = None
    for _b in odd_primes_under_k:
        for _a in range(-1 * _b, k + 1, 2):
            sequence = prime_quadratic_sequence(_a, _b)
            if len(sequence) > max_length:
                max_length = len(sequence)
                best_tuple = (_a, _b)
                best_sequence = sequence[:]
    return max_length, best_tuple, best_sequence

def Euler_Problem_28(n=1001):
    '''
    Starting with the number 1 and moving to the right in a clockwise direction a 5 by 5 spiral is formed as follows:
    21 22 23 24 25
    20  7  8  9 10
    19  6  1  2 11
    18  5  4  3 12
    17 16 15 14 13
    It can be verified that the sum of the numbers on the diagonals is 101.
    What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?
    '''
    # insight: we can totally get away with flattening the spiral. Then we are essentially trying to find the sum of a subsequence with a certain spacing pattern.
    # more insight: for each square, the average of the four elements in the corners equals the middle element on the left side.
    # 3^2 - (3^2 - 1^2) * (3/8) = 3^2 * (5/8) + 1^2 * (3/8) = 6
    # 5^2 - (5^2 - 3^2) * (3/8) = 5^2 * (5/8) + 3^2 * (3/8) = 19
    
    def sum_corners(side_length):
        assert side_length % 2 == 1
        if side_length == 1:
            return 1
        return 4 * int(side_length ** 2 * (5/8) + (side_length - 2) ** 2 * (3/8))

    # add contribution from each layer
    total = 0
    for k in range(1, n+1, 2):
        total += sum_corners(k)

    return total

def Euler_Problem_29():
    '''
    Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:
    2^2=4,  2^3=8 ,  2^4=16,  2^5=32
    3^2=9,  3^3=27,  3^4=81,  3^5=243
    4^2=16, 4^3=64,  4^4=256, 4^5=1024
    5^2=25, 5^3=125, 5^4=625, 5^5=3125
    If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
    How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?
    '''
    # idea: integers and their factorizations map one-to-one and onto.
    # Powers can be stored using factorization dicts whose JSON representation are hashible and within the boundary of common data types.
    from subroutines import Factorizer, restore_from_factorization
    import json
    
    fac = Factorizer(bound=100)

    def raise_factorization(factorization, b):
        '''
        Raise a factorization to b-th power.
        '''
        factors = dict(factorization)
        for _key in factors.keys():
            factors[_key] *= b
        return factors

    def power(a, b):
        '''
        Compute a^b in factorial form.
        '''
        a_factorization = fac.factorize(a)
        a_b = raise_factorization(a_factorization, b) 
        return a_b

    all_powers = []
    for a in range(2, 101, 1):
        for b in range(2, 101, 1):
            a_to_the_b_th = power(a, b)
            all_powers.append(json.dumps(a_to_the_b_th, sort_keys=True))
    all_powers = [json.loads(_p) for _p in list(set(all_powers))]
    return [restore_from_factorization(_p) for _p in all_powers]

def Euler_Problem_30(k=5):
    '''
    Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:
    1634 = 1^4 + 6^4 + 3^4 + 4^4
    8208 = 8^4 + 2^4 + 0^4 + 8^4
    9474 = 9^4 + 4^4 + 7^4 + 4^4
    As 1 = 1^4 is not a sum it is not included.
    The sum of these numbers is 1634 + 8208 + 9474 = 19316.
    Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.
    '''
    def is_sum_of_digit_powers(num, power):
        '''
        Check if a number equals the sum of powers of its digits.
        '''
        digits = [int(_d) for _d in list(str(num))]
        sumpow = sum([_d ** power for _d in digits])
        if num == sumpow:
            return True
        else:
            return False

    num_that_meet_criterion = []
    # k * 10 ^ k is an upper bound for numbers that can meet the criterion
    for num in range(10, k * 10 ** k):
        if is_sum_of_digit_powers(num, k):
            num_that_meet_criterion.append(num)

    return num_that_meet_criterion

def Euler_Problem_31(n=200):
    '''
    In England the currency is made up of pound, £, and pence, p, and there are eight coins in general circulation:
    1p, 2p, 5p, 10p, 20p, 50p, £1 (100p) and £2 (200p).
    It is possible to make £2 in the following way:
    1*£1 + *50p + 2*20p + 1*5p + 1*2p + 3*1p
    How many different ways can £2 be made using any number of coins?
    '''
    from collections import defaultdict
    # define what values can a single coin take
    units = [1, 2, 5, 10, 20, 50, 100, 200]

    # keep a cache of the different ways a value can be composed from
    cache_combinations = {0: [{}]}

    def bump(combination, value):
        '''
        Add a coin to a combination.
        combination -- str-to-int mapping, e.g. {'1': 2} for 2*1p coins.
        '''
        new_combination = defaultdict(int)
        new_combination.update(combination)
        new_combination[value] += 1
        return new_combination

    # just like DP but greedily, define recursion with cache
    def subproblem(m, cache):
        '''
        Compute all the number of ways to get to m pences.
        '''
        import json
        if m in cache.keys():
            return cache[m]
        else:
            combinations = []
            for _unit in units:
                if m >= _unit:
                    for _combination in subproblem(m - _unit, cache):
                        combinations.append(json.dumps(bump(_combination, str(_unit)), sort_keys=True))
            combinations = [json.loads(_d) for _d in list(set(combinations))]
            cache[m] = combinations
            return combinations
    
    return subproblem(n, cache_combinations)

def Euler_Problem_32():
    '''
    We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once; for example, the 5-digit number, 15234, is 1 through 5 pandigital.
    The product 7254 is unusual, as the identity, 39 * 186 = 7254, containing multiplicand, multiplier, and product is 1 through 9 pandigital.
    Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.
    HINT: Some products can be obtained in more than one way so be sure to only include it once in your sum.
    '''
    from subroutines import is_m_to_n_pandigital
    # brute-force scan as this problem has bounded complexity
    pandigital_products = []
    for first_number in range(1, 100):
        for second_number in range(100, 10000):
            product = first_number * second_number
            concatenated = ''.join(list(map(str, [first_number, second_number, product])))
            if is_m_to_n_pandigital(concatenated, 1, 9):
                pandigital_products.append(product)

    pandigital_products = list(set(pandigital_products))
    return pandigital_products

def Euler_Problem_33():
    '''
    The fraction 49/98 is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that 49/98 = 4/8, which is correct, is obtained by cancelling the 9s.
    We shall consider fractions like, 30/50 = 3/5, to be trivial examples.
    There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.
    If the product of these four fractions is given in its lowest common terms, find the value of the denominator.
    '''
    suitable_fractions = []
    for common_digit in range(1, 10):
        for numer_digit in range(1, 10):
            # the fraction has to be less than one
            for denom_digit in range(numer_digit+1, 10):
                numer_candidates = [10 * common_digit + numer_digit, 10 * numer_digit + common_digit]
                denom_candidates = [10 * common_digit + denom_digit, 10 * denom_digit + common_digit]
                for numer in numer_candidates:
                    for denom in denom_candidates:
                        fraction = numer / denom
                        if fraction == numer_digit / denom_digit:
                            suitable_fractions.append((numer, denom))
    return suitable_fractions    

def Euler_Problem_34():
    '''
    145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.
    Find the sum of all numbers which are equal to the sum of the factorial of their digits.
    Note: as 1! = 1 and 2! = 2 are not sums they are not included.
    '''
    from subroutines import factorial
    def sum_of_digit_factorials(num):
        return sum([factorial(int(_d)) for _d in list(str(num))])
    # 9! = 362880 < 10^6, so a number with p digits corresponds to a number bounded by p * 10^6.
    # -> the maximum value of p is 7. Simple brute-force solution works.
    suitable_numbers = []
    for num in range(3, 10 ** 7):
        if num == sum_of_digit_factorials(num):
            suitable_numbers.append(num)
    return suitable_numbers

def Euler_Problem_35(n=1000000):
    '''
    The number, 197, is called a circular prime because all rotations of the digits: 197, 971, and 719, are themselves prime.
    There are thirteen such primes below 100: 2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, and 97.
    How many circular primes are there below one million?
    '''
    from subroutines import all_primes_under

    def rotate(num):
        '''
        Rotate digits of a number and return all possibilities.
        '''
        str_form = str(num)
        return [int(str_form[i:] + str_form[:i]) for i in range(len(str_form))]

    primes = set(all_primes_under(n))

    # use a dict to deduplicate
    circular_primes = {}
    for _p in primes:
        rotations = rotate(_p)
        # determine if _p is a circular prime
        _circular = True
        for _q in rotations:
            if not _q in primes:
                _circular = False
        # if circular, collect the numbers 
        if _circular:
            for _q in rotations:
                circular_primes[_q] = 1

    return list(circular_primes.keys())

def Euler_Problem_36(n=1000000):
    '''
    The decimal number, 585 = 1001001001_2 (binary), is palindromic in both bases.
    Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.
    (Please note that the palindromic number, in either base, may not include leading zeros.)
    '''
    from subroutines import is_a_palindrome
    def base_10_to_binary(num):
        return int(bin(num)[2:])

    double_palindromes = []
    for k in range(1, n):
        binary_form = base_10_to_binary(k)
        if is_a_palindrome(k) and is_a_palindrome(binary_form):
            double_palindromes.append(k)
    
    return double_palindromes
   
def Euler_Problem_37(bound=1000000):
    '''
    The number 3797 has an interesting property. Being prime itself, it is possible to continuously remove digits from left to right, and remain prime at each stage: 3797, 797, 97, and 7. Similarly we can work from right to left: 3797, 379, 37, and 3.
    Find the sum of the only eleven primes that are both truncatable from left to right and right to left.
    NOTE: 2, 3, 5, and 7 are not considered to be truncatable primes.
    '''
    from subroutines import all_primes_under

    def get_truncations(num):
        '''
        Truncate the digits of a number and return all possibilities.
        '''
        str_form = str(num)
        truncations = [num]
        for start_index in range(1, len(str_form)):
                substring_l = str_form[:start_index]
                substring_r = str_form[start_index:]
                truncations.append(int(substring_l))
                truncations.append(int(substring_r))
        return list(set(truncations))

    primes = set(all_primes_under(bound))

    truncatable_primes = dict()
    for _p in primes:
        # base case: exclude primes that have only one digit
        if _p < 10:
            continue
        # for other numbers, consider all truncations
        truncations = get_truncations(_p)
        truncatable = True
        for _t in truncations:
            if not _t in primes:
                truncatable = False
                break
        if truncatable:
            truncatable_primes[_p] = 1
    return list(truncatable_primes.keys())

def Euler_Problem_38():
    '''
    Take the number 192 and multiply it by each of 1, 2, and 3:
    192 × 1 = 192
    192 × 2 = 384
    192 × 3 = 576
    By concatenating each product we get the 1 to 9 pandigital, 192384576. We will call 192384576 the concatenated product of 192 and (1,2,3)
    The same can be achieved by starting with 9 and multiplying by 1, 2, 3, 4, and 5, giving the pandigital, 918273645, which is the concatenated product of 9 and (1,2,3,4,5).
    What is the largest 1 to 9 pandigital 9-digit number that can be formed as the concatenated product of an integer with (1,2, ... , n) where n > 1?
    '''
    from subroutines import is_m_to_n_pandigital
    # the greatest number of digits that the base number can have is 4.
    pandigital_products = []
    for _base in range(1, 10 ** 4 - 1):
        # n is bounded between 2 and 9 inclusive
        for _n in range(2, 10):
            products = [_base * _v for _v in range(1, _n+1)]
            concatenated_product = ''.join(list(map(str, products)))
            if is_m_to_n_pandigital(concatenated_product, 1, 9):
                pandigital_products.append(concatenated_product)
    return pandigital_products

def Euler_Problem_39(max_perimeter=1000):
    '''
    If p is the perimeter of a right angle triangle with integral length sides, {a,b,c}, there are exactly three solutions for p = 120.
    {20,48,52}, {24,45,51}, {30,40,50}
    For which value of p ≤ 1000, is the number of solutions maximised?
    '''
    # assume a^2 + b^2 = c^2 and a <= b < c.
    # a + b > c  -> c < (max_perimeter+1) // 2.
    from math import sqrt, floor, ceil
    # this upper bound is exclusive
    upper_bound_c = (max_perimeter+1) // 2

    # first pre-compute perfect squares under c^2.
    # Then build on top of two-sum to determine Pythagorean sides.
    from subroutines import two_sum
    from collections import defaultdict
    perfect_squares = [_i ** 2 for _i in range(1, upper_bound_c)]
    perfect_squares_set = set(perfect_squares) 
    solution_count = defaultdict(int)
    for c_squared in perfect_squares:
        a_sq_b_sq_combinations = two_sum(perfect_squares_set, c_squared)
        for a_squared, b_squared in a_sq_b_sq_combinations:
            perimeter = int(sqrt(a_squared) + sqrt(b_squared) + sqrt(c_squared))
            solution_count[perimeter] += 1
    return max(list(solution_count.keys()), key=lambda x: solution_count[x])

def Euler_Problem_40():
    '''
    An irrational decimal fraction is created by concatenating the positive integers:
    0.123456789101112131415161718192021...
    It can be seen that the 12th digit of the fractional part is 1.
    If dn represents the nth digit of the fractional part, find the value of the following expression.
    d1 × d10 × d100 × d1000 × d10000 × d100000 × d1000000
    '''
    def get_n_digits(n):
        '''
        Compute n digits of the fractional part of the irrational number.
        '''
        retarr = []
        num = 0
        while len(retarr) < n:
            num += 1
            retarr += list(map(int, list(str(num))))
        return retarr
   
    # brute-force the first 1000000 digits
    arr = get_n_digits(1000000)
    indices_plus_one = [1, 10, 100, 1000, 10000, 100000, 1000000]
    retval = 1
    for _i in indices_plus_one:
        retval *= arr[_i - 1]
    return retval

def Euler_Problem_41():
    '''
    We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once. For example, 2143 is a 4-digit pandigital and is also prime.
    What is the largest n-digit pandigital prime that exists?
    '''
    from subroutines import all_primes_under, is_m_to_n_pandigital
    # any 9-digit or 8-digit pandigital number must be divisible by 3, because its sum of digits is 45 or 36, respectively
    # thus the largest n-digit pandigital number cannot have more than 7 digits
    primes = set(all_primes_under(10 ** 7))
    pandigital_primes = []
    for _p in primes:
        num_digits = len(str(_p))
        if is_m_to_n_pandigital(_p, 1, num_digits):
            pandigital_primes.append(_p)
    return pandigital_primes

def Euler_Problem_42():
    '''
    The nth term of the sequence of triangle numbers is given by, tn = ½n(n+1); so the first ten triangle numbers are:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    By converting each letter in a word to a number corresponding to its alphabetical position and adding these values we form a word value. For example, the word value for SKY is 19 + 11 + 25 = 55 = t10. If the word value is a triangle number then we shall call the word a triangle word.
    Using words.txt (right click and 'Save Link/Target As...'), a 16K text file containing nearly two-thousand common English words, how many are triangle words?
    '''
    from custom_config import get_attachment_path 
    from subroutines import is_triangular
    with open(get_attachment_path(42), 'r') as f:
        words = [eval(_x) for _x in f.read().split(',')]
    char_to_int = {
            'A':  1, 'B':  2, 'C':  3, 'D':  4, 'E':  5, 'F':  6, 'G':  7,
            'H':  8, 'I':  9, 'J': 10, 'K': 11, 'L': 12, 'M': 13, 'N': 14,
            'O': 15, 'P': 16, 'Q': 17, 'R': 18, 'S': 19, 'T': 20, 'U': 21,
            'V': 22, 'W': 23, 'X': 24, 'Y': 25, 'Z': 26
            }

    def word_to_score(word):
        return sum([char_to_int[_char] for _char in list(word)])
    
    triangle_count = 0
    for _word in words:
        if is_triangular(word_to_score(_word)):
            triangle_count += 1
    return triangle_count

def Euler_Problem_43():
    '''
    The number, 1406357289, is a 0 to 9 pandigital number because it is made up of each of the digits 0 to 9 in some order, but it also has a rather interesting sub-string divisibility property.
    Let d1 be the 1st digit, d2 be the 2nd digit, and so on. In this way, we note the following:
    d2d3d4=406 is divisible by 2
    d3d4d5=063 is divisible by 3
    d4d5d6=635 is divisible by 5
    d5d6d7=357 is divisible by 7
    d6d7d8=572 is divisible by 11
    d7d8d9=728 is divisible by 13
    d8d9d10=289 is divisible by 17
    Find the sum of all 0 to 9 pandigital numbers with this property.
    '''
    from subroutines import permutations_m_to_n_str
    idx_to_prime = {2: 2, 3: 3, 4: 5, 5: 7, 6: 11, 7: 13, 8: 17}

    divisible_pandigitals = []
    # all candidates come from 0-to-9 permutations that evaluate to more than 10^9
    candidates = [int(str_form) for str_form in permutations_m_to_n_str(0, 9)]
    candidates = [_c for _c in candidates if _c > 10**9]
    # check one by one for the specified criterion
    for candidate in candidates:
        divisible = True
        str_form  = str(candidate)
        for _idx, _prime in idx_to_prime.items():
            subint = int(str_form[(_idx-1):(_idx+2)])
            if not subint % _prime == 0:
                divisible = False
                break
        if divisible:
            divisible_pandigitals.append(candidate)
    return divisible_pandigitals

def Euler_Problem_44():
    '''
    Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
    '''
    from subroutines import two_sum, get_pentagonals
    pentagonals = set(get_pentagonals(10000)) 
    # Assume Pj < Pk. Then D + Pj = Pk, Pj + Pk = Pl, another pentagonal number.
    # Building on top of 2-Sum seems a good idea.
    # Note that D might be greater than Pj.
    two_sum_solutions = {}
    for _p in pentagonals:
        two_sum_solutions[_p] = two_sum(pentagonals, _p)

    min_d = -1
    best_tuple = None
    # Loop through all two-sum solutions
    for _pl, combinations in two_sum_solutions.items():
        for _pj, _pk in combinations:
            _d = _pk - _pj
            if _d in pentagonals:
                if min_d < 0 or min_d > _d:
                    min_d = _d
                    best_tuple = {'D': _d, 'Pj': _pj, 'Pk': _pk, 'Pj + Pk': _pl}
    return best_tuple

def Euler_Problem_45(trial_index=100000):
    '''
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
    Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
    Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
    It can be verified that T285 = P165 = H143 = 40755.
    Find the next triangle number that is also pentagonal and hexagonal.
    '''
    from subroutines import get_triangulars, get_pentagonals, get_hexagonals
    from collections import defaultdict

    # note that the ratio of triangular:pentagonal:hexagonal values for the same index is roughly 1:3:4, so an index range ratio of roughly 12:7:6 is appropriate with ~n^2 value-index scaling
    triangulars = get_triangulars(trial_index)
    pentagonals = get_pentagonals(int(trial_index * 7 / 12))
    hexagonals  = get_hexagonals(int(trial_index / 2))

    # use a dict for quick lookup and counting
    contributions = defaultdict(int)
    qualified = []
    for _L in [triangulars, pentagonals, hexagonals]:
        for _key in _L:
            contributions[_key] += 1
            if contributions[_key] == 3:
                qualified.append(_key)
    return qualified

def Euler_Problem_46(trial_bound=10**4):
    '''
    It was proposed by Christian Goldbach that every odd composite number can be written as the sum of a prime and twice a square.
    9 = 7 + 2×12
    15 = 7 + 2×22
    21 = 3 + 2×32
    25 = 7 + 2×32
    27 = 19 + 2×22
    33 = 31 + 2×12
    It turns out that the conjecture was false.
    What is the smallest odd composite that cannot be written as the sum of a prime and twice a square?
    '''
    from subroutines import all_primes_under
    from math import sqrt, ceil
    primes = set(all_primes_under(trial_bound))
    twice_squares = [2 * (x ** 2) for x in range(1, ceil(sqrt(trial_bound / 2)))]

    # brute-force all odd composite numbers
    for candidate in range(9, trial_bound, 2):
        is_composite = (not candidate in primes)
        if is_composite:
            summable = False
            for _tsq in twice_squares:
                target = candidate - _tsq
                if target in primes:
                    summable = True
                    break
            if not summable:
                return candidate
    return -1

def Euler_Problem_47(k=4, bound=10**6):
    '''
    The first two consecutive numbers to have two distinct prime factors are:
    14 = 2 × 7
    15 = 3 × 5
    The first three consecutive numbers to have three distinct prime factors are:
    644 = 2² × 7 × 23
    645 = 3 × 5 × 43
    646 = 2 × 17 × 19.
    Find the first four consecutive integers to have four distinct prime factors each. What is the first of these numbers?
    '''
    from subroutines import Factorizer
    # scan all integers in the interval [2, bound] until a tuple is found
    fac = Factorizer(bound=bound)
    trial = 1
    consecutive_qualified = 0
    while trial < bound:
        trial += 1
        _factorization = fac.factorize(trial)
        if len(_factorization.keys()) == k:
            consecutive_qualified += 1
            if consecutive_qualified == k:
                return (trial - k + 1)
        else:
            consecutive_qualified = 0
    return -1

def Euler_Problem_48(n=1000):
    '''
    The series, 1^1 + 2^2 + 3^3 + ... + 10^10 = 10405071317.

    Find the last ten digits of the series, 1^1 + 2^2 + 3^3 + ... + 1000^1000.
    '''
    from subroutines import Modulos

    # we can perform all computations in Z_(10^10) since we only care about the last ten digits
    Z = Modulos(10**10)
    retval = 0
    for k in range(1, n+1):
        val = 1
        for i in range(0, k):
            val = Z.multiply(val, k)
        retval = Z.add(retval, val)
    return retval

def Euler_Problem_49():
    '''
    The arithmetic sequence, 1487, 4817, 8147, in which each of the terms increases by 3330, is unusual in two ways: (i) each of the three terms are prime, and, (ii) each of the 4-digit numbers are permutations of one another.
    There are no arithmetic sequences made up of three 1-, 2-, or 3-digit primes, exhibiting this property, but there is one other 4-digit increasing sequence.
    What 12-digit number do you form by concatenating the three terms in this sequence?
    '''
    # idea: the 3-term arithmetic sequence problem can be reduced to the two-sum problem.
    # idea: the permutation check can be reduced to counter dict comparison.
    from subroutines import all_primes_under, two_sum
    from collections import Counter

    # compute all primes in range
    primes_list = all_primes_under(10000)
    primes = set(primes_list)
    
    # check all primes
    qualified_tuples = []
    for _p in primes_list:
        combinations = two_sum(primes, 2 * _p)
        for _a, _b in combinations:
            # filter trivial cases
            if _a == _p or _b == _p:
                continue
            # use dict comparison to check permutations
            if Counter(str(_a)) == Counter(str(_p)) and Counter(str(_b)) == Counter(str(_p)):
                qualified_tuples.append((_a, _p, _b))
    return qualified_tuples

def Euler_Problem_50(bound=10**6):
    '''
    The prime 41, can be written as the sum of six consecutive primes:
    41 = 2 + 3 + 5 + 7 + 11 + 13
    This is the longest sum of consecutive primes that adds to a prime below one-hundred.
    The longest sum of consecutive primes below one-thousand that adds to a prime, contains 21 terms, and is equal to 953.
    Which prime, below one-million, can be written as the sum of the most consecutive primes?
    '''
    from subroutines import all_primes_under
    primes_list = all_primes_under(bound)
    primes = set(primes_list)

    longest_chain = []
    for i, _p in enumerate(primes_list):
        # initialize the chain that starts with index i
        j = i
        partial_sum = 0
        chain = []
        # extend chain until partial sum goes out of range
        while True:
            chain.append(primes_list[j])
            partial_sum += primes_list[j]
            j += 1
            if partial_sum >= bound or j >= len(primes_list):
                break
            # if not out of range, compare with best chain so far
            if partial_sum in primes and len(chain) > len(longest_chain):
                longest_chain = chain[:]
    return longest_chain
        

